/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/numberKeyboard/App.vue')['default']
    copy: typeof import('./src/components/numberKeyboard copy/virtualInput copy.vue')['default']
    Edit: typeof import('./src/components/numberKeyboard/edit.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NumberKeyboard: typeof import('./src/components/numberKeyboard/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanField: typeof import('vant/es')['Field']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VirtualInput: typeof import('./src/components/numberKeyboard/virtualInput.vue')['default']
    VirtualKeyboard: typeof import('./src/components/numberKeyboard/virtualKeyboard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
